language: node_js
node_js:
  - "10.15.3"
sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/node_modules
    - $HOME/.config/yarn/global/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add expo-cli@3.11.9
install:
  - yarn install
script:
  - yarn test
deploy:
  provider: script
  skip_cleanup: true
  script: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive && expo publish
  on:
    branch: master
