os: linux
language: node_js
node_js:
  - "10.15.3"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/node_modules
    - $HOME/.config/yarn/global/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn test
deploy:
  provider: script
  script: sh travis/deploy.sh
  on:
    branch: production
