language: node_js
node_js:
  - "10.15.3"
sudo: false

branches:
  only:
    - master
env:
  global:
    - YARN_VERSION="1.21.1"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add expo-cli
install:
  - yarn install
script:
  - yarn test
deploy:
  provider: script
  skip_cleanup: true
  script: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive && expo publish
  on:
    tags: true
